#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle

numlockx &
udiskie -s &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 5h > "$XDG_RUNTIME_DIR/ssh-agent.env"
    trap "kill $SSH_AGENT_PID" 0 # kill ssh-agent at logout
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

sleep 3
autorandr --change &
xplugd &
setxkbmap -layout us -variant altgr-intl -option nodeadkeys
xfce4-power-manager &
ibus-daemon -drx
blueman-applet &
source /usr/bin/virtualenvwrapper.sh

# Touchpad settings
## Touchpad id is 12
## Acceleration: value is float between 0 and 1.
xinput set-prop 12 'libinput Accel Speed' 0.2
xinput set-prop 12 'libinput Accel Speed' 0.2
xinput disable 12
# Trackpoint settings
## Trackpoint id is 13
xinput --set-prop "13" "libinput Accel Speed" 0.2
vmon setup &
joplin-desktop &
